version: "3.8"

services:
  backend:
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8090:8090" # Add this back to expose backend
    container_name: fastapi-backend-prod
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8090 || exit 1"]
    networks:
      - semantic-search-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    container_name: react-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - semantic-search-network

networks:
  semantic-search-network:
    driver: bridge
